FROM python:3
WORKDIR /last_messages
COPY . .
RUN pip install -r requirements.txt
ENV API_ID=you_api_id
ENV API_HASH=your_api_hash
ENV PHONE=your_phone_number
ENV BOT_TOKEN=7022593864:AAFALynpfYMqQjdaKKlIXR2rMdFXyAiHMV4z
ENV DB_URL=postgresql://user:qwe123@postgre:5432/messagesdb